Repository Am10aN16/hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#2 flower animation
  CSS Animations/flower/index.html
  CSS Animations/flower/style.css
Labels: hacktoberfest

#8 Create AnimatedSpinner.html
  CSS Animations/AnimatedSpinner.html
Labels: hacktoberfest

#19 3 d toggle switch
  index3.html
  style.css
Labels: hacktoberfest

#20 Neon Blossom Dance
  CSS Animations/Neon Blossom Dance/index.html
  CSS Animations/Neon Blossom Dance/styles.css
Labels: hacktoberfest

#13 Create loder.css
  CSS Animations/loder.css
Labels: hacktoberfest

#9 xyz031 added
  Clock animation/c.png
  Clock animation/index.html
  Clock animation/s.css
Labels: hacktoberfest

#11 css animation
  CSS Animations/anim8css/index.html
  CSS Animations/anim8css/style.css
Labels: hacktoberfest

#14 CSS Animated Clock #5
  CSS Animations/clock.js
  clock.css
  clock.html
Labels: hacktoberfest

#15 Create animation1.css
  CSS Animations/animation1.css
Labels: good first issue, hacktoberfest

#17 Added Darknight Animation
  DarkNight/2.png
  DarkNight/3.png
  DarkNight/index.html
  DarkNight/styles.css
Labels: good first issue, hacktoberfest

#18 added smiley animation
  CSS Animations/smiley/index.html
  CSS Animations/smiley/style.css
Labels: enhancement, good first issue, hacktoberfest

#26 Blob Effect Add in CSS
  index.html
  style.css
Labels: good first issue, hacktoberfest

#27 Added text animations
  CSS Animations/text-animations/index.html
  CSS Animations/text-animations/style.css
Labels: good first issue, hacktoberfest

#28 Create PencilTypeLoadingSpinner.html
  CSS Animations/PencilTypeLoadingSpinner.html
Labels: enhancement, hacktoberfest

#29 Create css-glow-effect-preloader.html
  CSS Animations/css-glow-effect-preloader.html
Labels: enhancement, hacktoberfest

#30 Added tilting profile card animation on hover..
  CSS Animations/Tilting_Profile_Card/index.html
  CSS Animations/Tilting_Profile_Card/style.css
  CSS Animations/Tilting_Profile_Card/vanilla-tilt.js
Labels: good first issue, hacktoberfest

#31 Pulsing effect using CSS3 Transform Scale
  CSS Animations/Pulsing effect/index.html
  CSS Animations/Pulsing effect/style.css
Labels: good first issue, hacktoberfest

#32 Loader Animation added
  Loader/loader.css
  Loader/loader.html
Labels: enhancement, hacktoberfest

#36 Revert "Create css-glow-effect-preloader.html"
  CSS Animations/css-glow-effect-preloader.html
Labels: enhancement, hacktoberfest

#38 3D toggle switch added
  pulse.css
  pulse.html
  toggle.css
  toggle.html
Labels: good first issue, hacktoberfest

#40 Update style.css
  style.css
Labels: enhancement, good first issue, hacktoberfest

#42 Create Pulsing effect using CSS3 Transform Scale #6
  Pulsing effect using CSS3 Transform Scale #6
Labels: enhancement, good first issue, hacktoberfest

#41 Add files for the project Game Changer
  GameChanger/assets/IMG_7564.JPG
  GameChanger/assets/IMG_7565.JPG
  GameChanger/assets/IMG_7566.JPG
  GameChanger/assets/IMG_7567.JPG
  GameChanger/assets/IMG_7568.JPG
  GameChanger/assets/raybanlogo.png
  GameChanger/index.html
  GameChanger/javascript.js
  GameChanger/styles.css
Labels: enhancement, good first issue, hacktoberfest

#50 Busy Traffic Animation
  Busy Traffic/Images/background.jpg
  Busy Traffic/Images/mincar.png
  Busy Traffic/Images/mincar2.png
  Busy Traffic/Images/mincar3.png
  Busy Traffic/Images/mincar4.png
  Busy Traffic/Images/mincar5.png
  Busy Traffic/Images/mincar6.png
  Busy Traffic/Images/mincar7.png
  Busy Traffic/Images/mincar8.png
  Busy Traffic/Images/mincar9.png
  Busy Traffic/index.html
  Busy Traffic/style.css
Labels: enhancement, hacktoberfest

#44 Added moving square that changes colors
  square.html
Labels: good first issue, hacktoberfest

#55 Adjust Clock Hand Animation Speed for Realistic Timekeeping
  Clock animation/s.css
Labels: documentation, enhancement, good first issue, hacktoberfest

#58 parallax animation
  CSS Animations/parallax scrolling/index.html
  CSS Animations/parallax scrolling/style.css
Labels: enhancement, hacktoberfest
